### ISSUE TITLE
Requesting Truck With Bail Price

### ISSUE THREAD

**Issue by KodakZack** [Annalouu/an-towjob#10]
I currently have the bail price set to 500$ and if you third eye the person to take out the flatbed and you do not have the money it will tell you that you dont have enough but it breaks the ped.

After you do this and try to get the truck again it only allows you to try to store the vehicle but you cant as you didnt have the money this first time.
![FiveM_b2699_GTAProcess_dMs1CuycVr](https://github.com/Annalouu/an-towjob/assets/119061087/90a54c67-c937-499e-b1aa-e5e4238f525e)

**Comment by KodakZack** [comment]
My work around was to charge them the money and spawn the car anyways and have the notification tell them they are also in debt.

**Comment by Annalouu** [comment]
Well you can add a check if they dont have the money the truck doesnt spawn

**Comment by KodakZack** [comment]
The issue is that it doesnt actually spawn the truck. It thinks it does and then you can only interact with the ped to "return" the truck.

With the current event it shouldnt even try to spawn the truck if you dont have the money as it only has the notify event.

**Comment by Annalouu** [comment]
Its this function:

RegisterNetEvent('an-tow:client:TakeOutVehicle', function(data)
    local coords = Config.Locations["vehicle"].coords
    coords = vector3(coords.x, coords.y, coords.z)
    local ped = PlayerPedId()
    local pos = GetEntityCoords(ped)
    towout = true
        local vehicleInfo = data.vehicle
        TriggerServerEvent('an-tow:server:DoBail', true, vehicleInfo)
        selectedVeh = vehicleInfo
end)

**Comment by KodakZack** [comment]
Oh I see now. Thank you!
